# Generated by Django 5.2.3 on 2025-06-22 21:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='bot_message',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user_message',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], default='user', max_length=50),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.chatsession'),
        ),
    ]
